version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: consensus_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: consensus_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d consensus_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 